# Coleções

## Tuplas

In [104]:
tupla = ('Palmeiras', 'Corinthians', 'São Paulo')   ### são ordenados e imutáveis ####

In [105]:
tupla

('Palmeiras', 'Corinthians', 'São Paulo')

In [106]:
tupla[0]    #### tupla[0] pega o elemento da posição 0 ###

'Palmeiras'

In [107]:
tupla.index('Corinthians')    ### o comando index busca a posição do elemento na tupla #####

1

In [108]:
for i in tupla:
  print(i)

Palmeiras
Corinthians
São Paulo


## Listas

In [109]:
l1 = ['Palmeiras', 'Corinthians', 'São Paulo']    ### são ordenadas e mutáveis ###
l2 = ['Flamengo', 'Vasco']

In [110]:
l3 = l1 + l2
print(l3)

['Palmeiras', 'Corinthians', 'São Paulo', 'Flamengo', 'Vasco']


In [111]:
l2

['Flamengo', 'Vasco']

In [112]:
l2_2 = l2 * 2
print(l2_2)

['Flamengo', 'Vasco', 'Flamengo', 'Vasco']


In [113]:
l1[0]    #### l1[0] pega o elemento da posição 0 ###

'Palmeiras'

In [114]:
l1

['Palmeiras', 'Corinthians', 'São Paulo']

In [115]:
l1[0:2]

['Palmeiras', 'Corinthians']

In [116]:
l1.append('Santos')    ### adiciona um elelemnto na lista #####
print(l1)

['Palmeiras', 'Corinthians', 'São Paulo', 'Santos']


In [117]:
l1.remove('Santos')     ### o comando remove remove um elelemnto da lista ###
print(l1)

['Palmeiras', 'Corinthians', 'São Paulo']


In [118]:
del(l1)

In [119]:
print(l1)

NameError: name 'l1' is not defined

In [ ]:
for i in l2_2:
  print(i)

## Dicionários

In [120]:
dicionario = {'Palmeiras': 12, 'Corinthians': 7, 'São Paulo': 6} ## armazenam dados ordenados em pares chave-valor###

In [121]:
dicionario['São Paulo']

6

In [122]:
dicionario['Santos'] = 8   #### acrescenta um elemento no dicionário ####

In [123]:
print(dicionario)

{'Palmeiras': 12, 'Corinthians': 7, 'São Paulo': 6, 'Santos': 8}


In [124]:
del(dicionario)['Corinthians']    ### del = apaga um elemento no dicionário ##
print(dicionario)

{'Palmeiras': 12, 'São Paulo': 6, 'Santos': 8}


In [125]:
dicionario.items() ### item para visualizar o dicionário inteiro ###

dict_items([('Palmeiras', 12), ('São Paulo', 6), ('Santos', 8)])

In [126]:
dicionario.keys()    #### keys traz apenas as chaves sem os valores ###

dict_keys(['Palmeiras', 'São Paulo', 'Santos'])

In [127]:
dicionario.values()   ### traz os valores das chaves ####

dict_values([12, 6, 8])

In [128]:
dicionario2 = {'Flamengo': 8, 'Vasco': 4}
print(dicionario2)

{'Flamengo': 8, 'Vasco': 4}


In [129]:
dicionario.update(dicionario2)    ### update junta os valores de dois dicionários ##
print(dicionario)

{'Palmeiras': 12, 'São Paulo': 6, 'Santos': 8, 'Flamengo': 8, 'Vasco': 4}


In [130]:
dicionario.items()   ### retorna chave-valor ####

dict_items([('Palmeiras', 12), ('São Paulo', 6), ('Santos', 8), ('Flamengo', 8), ('Vasco', 4)])

In [131]:
for i, j in dicionario.items():
  print(f'Time: {i}, número de títulos do brasileirão: {j}')  ##f para formatação de string (para pegar a chave-valor) ###

Time: Palmeiras, número de títulos do brasileirão: 12
Time: São Paulo, número de títulos do brasileirão: 6
Time: Santos, número de títulos do brasileirão: 8
Time: Flamengo, número de títulos do brasileirão: 8
Time: Vasco, número de títulos do brasileirão: 4


## Conjuntos (set)

In [132]:
times = {'Palmeiras', 'Corinthians', 'São Paulo', 'Palmeiras',
                'Corinthians', 'Santos', 'Santos', 'Santos'}  ## não ordenados e armazenam elementos únicos ###

In [133]:
print(times)

{'Palmeiras', 'São Paulo', 'Corinthians', 'Santos'}


In [134]:
print(set(times))   ### set seleciona os elementos q não se repetem ###

{'Palmeiras', 'São Paulo', 'Corinthians', 'Santos'}


In [135]:
c1 = {1,2,3,4,5}
c2 = {3,4,5,6,7}
c3 = c1.intersection(c2)

In [136]:
print(c3)

{3, 4, 5}


In [137]:
c1.difference(c2)   ### C1 - C2 ###

{1, 2}

In [138]:
c2.difference(c1)   ### C2 - C1 ###

{6, 7}

#**Vetores**

In [139]:
import numpy as np
####A biblioteca Numerical Python (NumPy) é usada principalmente para trabalhar com números, vetores e matrizes de forma rápida e eficiente no Python.

In [140]:
vetor = np.array([10, 20, 30, 40])

In [141]:
vetor

array([10, 20, 30, 40])

In [142]:
print(vetor)

[10 20 30 40]


In [143]:
vetor[2]   ### pega o elemento que está na posição 2

np.int64(30)

In [144]:
print(vetor[1])

20


In [145]:
len(vetor)  ### retorna o tamanho do vetor ####

4

In [146]:
vetor * 2

array([20, 40, 60, 80])

In [147]:
vetor + 10

array([20, 30, 40, 50])

In [148]:
vetor / 2

array([ 5., 10., 15., 20.])

In [149]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

In [150]:
a + b

array([11, 22, 33])

In [151]:
a * b

array([10, 40, 90])

In [152]:
notas = np.array([7, 5, 9, 8, 6])

In [153]:
np.sum(notas)

np.int64(35)

In [154]:
np.mean(notas)

np.float64(7.0)

In [155]:
np.max(notas)

np.int64(9)

In [156]:
np.min(notas)

np.int64(5)

In [157]:
for i in notas:
    print(i)

7
5
9
8
6


In [158]:
notas[notas >= 7]

array([7, 9, 8])

#**Matrizes**

In [159]:
import numpy as np

In [160]:
matriz = np.array([[2, 3, 1], [4, 5, 7]])

In [161]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [162]:
matriz.shape   ###shape é o comando para dizer o tipo da matriz ###

(2, 3)

In [163]:
matriz[0]

array([2, 3, 1])

In [164]:
matriz [1]

array([4, 5, 7])

In [165]:
matriz[0][1]    #### pega o elemento da linha 0 e coluna 1 ####

np.int64(3)

In [166]:
matriz[1][2]

np.int64(7)

In [167]:
for i in range(matriz.shape[0]):  #### shape[0] conta as linhas, no caso a 1 e matriz[i] pega o conteúdo da linha 1
  print(matriz[i])

[2 3 1]
[4 5 7]


In [168]:
for i in range(matriz.shape[0]):   ### mostra a linha inteira ###
  print(matriz[i])
  for j in range(matriz.shape[1]):  ### esse for de j percorre cada elemento dessa linha
    print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
